language: android
jdk: oraclejdk8

deploy:
  - provider: script
    script:
      ./gradlew generateReleaseNotes assembleDebug appDistributionUploadDebug
    on:
      branch: master
    skip_cleanup: true