language: android
jdk: oraclejdk8

branches:
  only:
    - master
    # Release Branches : "release-0.1"
    - /^release-\d+\.\d+$/
    # Release Tags: "0.1.0"
    - /^\d+\.\d+\.\d+$/

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script:
  #execute checkstyles, tests suite, linters, code analysis.
  - ./gradlew packageDebugUniversalApk packageReleaseUniversalApk

deploy:
  - provider: script
    script:
      ./gradlew generateReleaseNotes appDistributionUploadDebug
    on:
      branch: master
    skip_cleanup: true

  - provider: script
    script:
      ./gradlew appDistributionUploadRelease
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^release-.*$
    skip_cleanup: true

  - provider: script
    script:
      ./gradlew publishReleaseBundle
    on:
      tags: true
    skip_cleanup: true